var before = [
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Analytics",
    icon: "layers",
    jab: "",
    menu: "Dashboard",
    menuid: 121,
    nip: "15010001",
    path: "general/laporan/absen",
    print: "Y",
    route: "/absen,/absen/{periodeawal}/{periodeakhir},/checkabsen/{periodeawal}/{periodeakhir},/get_general_data",
    show: "Y",
    submenu: "Absen",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Analytics",
    icon: "view_list",
    jab: "",
    menu: "Dashboard",
    menuid: 101,
    nip: "15010001",
    path: "main-navigation/dashboard/analytics",
    print: "Y",
    route: "/FindDashboard,/Dashboard,/divisitim,/MasterList,/RealisasiCall,/get_general_data,/RencanaCall",
    show: "Y",
    submenu: "Call",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Master",
    icon: "layers",
    jab: "",
    menu: "Company",
    menuid: 116,
    nip: "15010001",
    path: "general/master/cabangarea",
    print: "Y",
    route: "/cabangareas",
    show: "Y",
    submenu: "Office",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Master",
    icon: "layers",
    jab: "",
    menu: "Company",
    menuid: 119,
    nip: "15010001",
    path: "general/master/divisi-tim",
    print: "Y",
    route: "/divisitim",
    show: "Y",
    submenu: "Divisi Team",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Master",
    icon: "layers",
    jab: "",
    menu: "Company",
    menuid: 114,
    nip: "15010001",
    path: "general/master/structure-gsm",
    print: "Y",
    route: "/structure,/terrigt,/customer,/outlets,/jmldata_structure,/terricust",
    show: "Y",
    submenu: "Structure",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Master",
    icon: "layers",
    jab: "",
    menu: "Company",
    menuid: 124,
    nip: "15010001",
    path: "general/master/bawahan",
    print: "Y",
    route: "/bawahan",
    show: "Y",
    submenu: "Management Access",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Master",
    icon: "policy",
    jab: "",
    menu: "Company",
    menuid: 136,
    nip: "15010001",
    path: "general/master/policy",
    print: "Y",
    route: "/targetcall,/get_general_data,/structure",
    show: "Y",
    submenu: "Policy",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Master",
    icon: "layers",
    jab: "",
    menu: "Customer",
    menuid: 123,
    nip: "15010001",
    path: "general/master/specialist",
    print: "Y",
    route: "/specialist,/bridge_product_spesialis",
    show: "Y",
    submenu: "Specialist",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Master",
    icon: "layers",
    jab: "",
    menu: "Customer",
    menuid: 145,
    nip: "15010001",
    path: "general/master/gelar-customer",
    print: "Y",
    route: "/gelar",
    show: "Y",
    submenu: "Gelar Customer",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Master",
    icon: "layers",
    jab: "",
    menu: "Customer",
    menuid: 144,
    nip: "15010001",
    path: "general/master/status-kerja",
    print: "Y",
    route: "/status_kerja",
    show: "Y",
    submenu: "Status Kerja",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Master",
    icon: "layers",
    jab: "",
    menu: "Customer",
    menuid: 143,
    nip: "15010001",
    path: "general/master/type-customer",
    print: "Y",
    route: "/tipe_customer",
    show: "Y",
    submenu: "Type Customer",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Master",
    icon: "layers",
    jab: "",
    menu: "Customer",
    menuid: 133,
    nip: "15010001",
    path: "general/master/jabatancust",
    print: "Y",
    route: "/jabcustomer",
    show: "Y",
    submenu: "Jabatan Customer",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Master",
    icon: "layers",
    jab: "",
    menu: "Customer",
    menuid: 108,
    nip: "15010001",
    path: "general/master/new-customer",
    print: "Y",
    route: "/customer_by_area,/customer,/jmldata_customer,/tipe_customer,/status_kerja,/customerImport",
    show: "Y",
    submenu: "New Customer",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Master",
    icon: "layers",
    jab: "",
    menu: "Customer",
    menuid: 112,
    nip: "15010001",
    path: "general/master/customer",
    print: "Y",
    route: "/customer_by_area,/customer,/tipe_customer,/status_kerja,/citys,/gelar,/jmldata_customer,/specialist,/customer_product,/customerImport",
    show: "Y",
    submenu: "Customer Doctor",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Master",
    icon: "layers",
    jab: "",
    menu: "Customer",
    menuid: 137,
    nip: "15010001",
    path: "general/master/non-customer",
    print: "Y",
    route: "/customer_by_area,/customer,/jmldata_customer,/customerImport",
    show: "Y",
    submenu: "Customer Non Doctor",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Master",
    icon: "layers",
    jab: "",
    menu: "Customer",
    menuid: 115,
    nip: "15010001",
    path: "general/master/customer-prioritas",
    print: "Y",
    route: "/customer_prioritas",
    show: "Y",
    submenu: "Customer Prioritas",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Master",
    icon: "layers",
    jab: "",
    menu: "Outlet",
    menuid: 140,
    nip: "15010001",
    path: "general/master/jenisoutlet",
    print: "Y",
    route: "/jenisoutlets",
    show: "Y",
    submenu: "Jenis Outlet",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Master",
    icon: "layers",
    jab: "",
    menu: "Outlet",
    menuid: 138,
    nip: "15010001",
    path: "general/master/new-outlet",
    print: "Y",
    route: "/outlets,/citys,/outletsImport",
    show: "Y",
    submenu: "New Outlet",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Master",
    icon: "layers",
    jab: "",
    menu: "Outlet",
    menuid: 125,
    nip: "15010001",
    path: "general/master/outlet",
    print: "Y",
    route: "/outlets,/citys,/jenisoutlets,/customer_by_area,/verified_outlet",
    show: "Y",
    submenu: "Outlet",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Master",
    icon: "layers",
    jab: "",
    menu: "Product",
    menuid: 113,
    nip: "15010001",
    path: "general/master/product",
    print: "Y",
    route: "/products,/product_details,/bridge_product_spesialis,/deletefile,/productsImport",
    show: "Y",
    submenu: "Product",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Master",
    icon: "layers",
    jab: "",
    menu: "Product",
    menuid: 122,
    nip: "15010001",
    path: "general/master/product-blast",
    print: "Y",
    route: "/productblast,/getproductblast",
    show: "Y",
    submenu: "Product Blast",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Master",
    icon: "layers",
    jab: "",
    menu: "Other",
    menuid: 120,
    nip: "15010001",
    path: "general/master/category",
    print: "Y",
    route: "/categoryactivity",
    show: "Y",
    submenu: "Category",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Master",
    icon: "layers",
    jab: "",
    menu: "Other",
    menuid: 118,
    nip: "15010001",
    path: "general/master/kitab",
    print: "Y",
    route: "/kitab,/deletefile",
    show: "Y",
    submenu: "Kitab",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Master",
    icon: "layers",
    jab: "",
    menu: "Other",
    menuid: 139,
    nip: "15010001",
    path: "general/master/kota",
    print: "Y",
    route: "/citys",
    show: "Y",
    submenu: "City",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Call",
    icon: "flag",
    jab: "",
    menu: "Master",
    menuid: 129,
    nip: "15010001",
    path: "general/master/master-list",
    print: "Y",
    route: "/terricust,/customer_by_area,/customer_product,/structure,/get_general_data,/MasterList,/products",
    show: "Y",
    submenu: "Master List",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Call",
    icon: "view_list",
    jab: "",
    menu: "Master",
    menuid: 130,
    nip: "15010001",
    path: "general/master/call-list",
    print: "Y",
    route: "/MasterList,/citys,/customer_by_area,/terrigt,/products,/customer_product,/structure,/PelaksanaanCall,/get_general_data,/RencanaCall",
    show: "Y",
    submenu: "Master Call List",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Call",
    icon: "library_books",
    jab: "",
    menu: "Action",
    menuid: 102,
    nip: "15010001",
    path: "general/master/monthly-call-plan",
    print: "Y",
    route: "/structure,/MasterList,/RencanaCall,/categoryactivity,/get_general_data",
    show: "Y",
    submenu: "Monthly Call Plan",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Call",
    icon: "check_circle",
    jab: "",
    menu: "Action",
    menuid: 103,
    nip: "15010001",
    path: "general/master/approve-rencana-call",
    print: "Y",
    route: "/customer_product,/MasterList,/citys,/customer_by_area,/terri_gt,/products,/CallOverview,/RencanaCall,/RencanaCallHistory,/structure,/get_general_data",
    show: "Y",
    submenu: "Approve Rencana Call",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Call",
    icon: "playlist_add_check",
    jab: "",
    menu: "Action",
    menuid: 104,
    nip: "15010001",
    path: "general/master/approve-realisasi-call",
    print: "Y",
    route: "/structure,/RealisasiReport,/RealisasiCall,/get_general_data",
    show: "Y",
    submenu: "Approve Realisasi Call",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Call",
    icon: "featured_play_list",
    jab: "",
    menu: "Report",
    menuid: 107,
    nip: "15010001",
    path: "general/laporan/pelaksanaan-call",
    print: "Y",
    route: "/PelaksanaanCall,/RencanaCall,/get_general_data,/PelaksanaanCallMobile,/RencanaCallMobile",
    show: "Y",
    submenu: "Draft Perencanaan Call",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Call",
    icon: "featured_video",
    jab: "",
    menu: "Report",
    menuid: 110,
    nip: "15010001",
    path: "general/laporan/perencanaan-call",
    print: "Y",
    route: "/PelaksanaanCall,/RencanaCall,/get_general_data",
    show: "Y",
    submenu: "Perencanaan Call",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Call",
    icon: "map",
    jab: "",
    menu: "Report",
    menuid: 106,
    nip: "15010001",
    path: "general/laporan/map-call",
    print: "Y",
    route: "/mapcall,/get_general_data",
    show: "Y",
    submenu: "Map Call",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Call",
    icon: "library_books",
    jab: "",
    menu: "Report",
    menuid: 128,
    nip: "15010001",
    path: "general/laporan/dcall",
    print: "Y",
    route: "/DetailCall,/structure,/get_general_data,/RealisasiCall",
    show: "Y",
    submenu: "Detail Call",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Call",
    icon: "next_week",
    jab: "",
    menu: "Report",
    menuid: 127,
    nip: "15010001",
    path: "general/laporan/report-realisasi",
    print: "Y",
    route: "/RealisasiReport,/RealisasiCall,/structure,/get_general_data",
    show: "Y",
    submenu: "Realisasi Call",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Call",
    icon: "receipt",
    jab: "",
    menu: "Report",
    menuid: 109,
    nip: "15010001",
    path: "general/laporan/call-overview",
    print: "Y",
    route: "/structure,/MasterList,/CallOverview,/get_general_data,/RencanaCall,/RealiasasiCall",
    show: "Y",
    submenu: "Call Overview",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "Call",
    icon: "playlist_add_check",
    jab: "",
    menu: "Report",
    menuid: 111,
    nip: "15010001",
    path: "general/laporan/evaluasi-report",
    print: "Y",
    route: "/EvaluasiReport,/RencanaCall,/get_general_data",
    show: "Y",
    submenu: "Evaluasi Call",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "General",
    icon: "toggle_on",
    jab: "",
    menu: "Admin",
    menuid: 126,
    nip: "15010001",
    path: "general/administration/menu",
    print: "Y",
    route: "/menus,/menus/{menu_id}",
    show: "Y",
    submenu: "Menu",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "General",
    icon: "toggle_on",
    jab: "",
    menu: "Admin",
    menuid: 131,
    nip: "15010001",
    path: "general/administration/menuauthentication",
    print: "Y",
    route: "/users,/menu_auths,/group_auth_menu,/menu_auth",
    show: "Y",
    submenu: "User Authentication",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "General",
    icon: "toggle_on",
    jab: "",
    menu: "Admin",
    menuid: 132,
    nip: "15010001",
    path: "general/administration/groupauthentication",
    print: "Y",
    route: "/group_auth,/group_auth_detail,/group_auth_menu",
    show: "Y",
    submenu: "Group Authentication",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "General",
    icon: "layers",
    jab: "",
    menu: "Admin",
    menuid: 117,
    nip: "15010001",
    path: "general/master/import-data",
    print: "Y",
    route: "/import_csv_tipe/{tipe},/import_csv_proses/{sp},/import_csv_table/{table},/multi_import_csv",
    show: "Y",
    submenu: "Import Data",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "General",
    icon: "layers",
    jab: "",
    menu: "Employee",
    menuid: 134,
    nip: "15010001",
    path: "general/master/category-cuti",
    print: "Y",
    route: "/kategori_cuti",
    show: "Y",
    submenu: "Category Cuti",
  },
  {
    CreateName: "",
    CreateTime: "0001-01-01T00:00:00Z",
    UpdateName: "",
    UpdateTime: "0001-01-01T00:00:00Z",
    add: "Y",
    aktif: "Y",
    delete: "Y",
    edit: "Y",
    groupmenu: "General",
    icon: "person",
    jab: "",
    menu: "Employee",
    menuid: 105,
    nip: "15010001",
    path: "general/master/approve-cuti",
    print: "Y",
    route: "/cuti,/get_general_data",
    show: "Y",
    submenu: "Approve Cuti",
  },
];
var after = [
  {
    group: "Analytics",
    menu: [
      {
        name: "Dashboard",
        icon: "layers",
        submenu: [
          {
            name: "Absen",
            route: "general/laporan/absen",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
          {
            icon: "view_list",
            name: "Call",
            route: "main-navigation/dashboard/analytics",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
        ],
      },
    ],
  },
  {
    group: "Master",
    menu: [
      {
        name: "Company",
        icon: "layers",
        submenu: [
          {
            name: "Office",
            route: "general/master/cabangarea",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
          {
            icon: "layers",
            name: "Divisi Team",
            route: "general/master/divisi-tim",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
          {
            icon: "layers",
            name: "Structure",
            route: "general/master/structure-gsm",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
          {
            icon: "layers",
            name: "Management Access",
            route: "general/master/bawahan",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
          {
            icon: "policy",
            name: "Policy",
            route: "general/master/policy",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
        ],
      },
      {
        name: "Customer",
        icon: "layers",
        submenu: [
          {
            name: "Specialist",
            route: "general/master/specialist",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
          {
            icon: "layers",
            name: "Gelar Customer",
            route: "general/master/gelar-customer",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
          {
            icon: "layers",
            name: "Status Kerja",
            route: "general/master/status-kerja",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
          {
            icon: "layers",
            name: "Type Customer",
            route: "general/master/type-customer",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
          {
            icon: "layers",
            name: "Jabatan Customer",
            route: "general/master/jabatancust",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
          {
            icon: "layers",
            name: "New Customer",
            route: "general/master/new-customer",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
          {
            icon: "layers",
            name: "Customer Doctor",
            route: "general/master/customer",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
          {
            icon: "layers",
            name: "Customer Non Doctor",
            route: "general/master/non-customer",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
          {
            icon: "layers",
            name: "Customer Prioritas",
            route: "general/master/customer-prioritas",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
        ],
      },
      {
        name: "Outlet",
        icon: "layers",
        submenu: [
          {
            name: "Jenis Outlet",
            route: "general/master/jenisoutlet",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
          {
            icon: "layers",
            name: "New Outlet",
            route: "general/master/new-outlet",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
          {
            icon: "layers",
            name: "Outlet",
            route: "general/master/outlet",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
        ],
      },
      {
        name: "Product",
        icon: "layers",
        submenu: [
          {
            name: "Product",
            route: "general/master/product",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
          {
            icon: "layers",
            name: "Product Blast",
            route: "general/master/product-blast",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
        ],
      },
      {
        name: "Other",
        icon: "layers",
        submenu: [
          {
            name: "Category",
            route: "general/master/category",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
          {
            icon: "layers",
            name: "Kitab",
            route: "general/master/kitab",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
          {
            icon: "layers",
            name: "City",
            route: "general/master/kota",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
        ],
      },
    ],
  },
  {
    group: "Call",
    menu: [
      {
        name: "Master",
        icon: "flag",
        submenu: [
          {
            name: "Master List",
            route: "general/master/master-list",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
          {
            icon: "view_list",
            name: "Master Call List",
            route: "general/master/call-list",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
        ],
      },
      {
        name: "Action",
        icon: "library_books",
        submenu: [
          {
            name: "Monthly Call Plan",
            route: "general/master/monthly-call-plan",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
          {
            icon: "check_circle",
            name: "Approve Rencana Call",
            route: "general/master/approve-rencana-call",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
          {
            icon: "playlist_add_check",
            name: "Approve Realisasi Call",
            route: "general/master/approve-realisasi-call",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
        ],
      },
      {
        name: "Report",
        icon: "featured_play_list",
        submenu: [
          {
            name: "Draft Perencanaan Call",
            route: "general/laporan/pelaksanaan-call",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
          {
            icon: "featured_video",
            name: "Perencanaan Call",
            route: "general/laporan/perencanaan-call",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
          {
            icon: "map",
            name: "Map Call",
            route: "general/laporan/map-call",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
          {
            icon: "library_books",
            name: "Detail Call",
            route: "general/laporan/dcall",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
          {
            icon: "next_week",
            name: "Realisasi Call",
            route: "general/laporan/report-realisasi",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
          {
            icon: "receipt",
            name: "Call Overview",
            route: "general/laporan/call-overview",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
          {
            icon: "playlist_add_check",
            name: "Evaluasi Call",
            route: "general/laporan/evaluasi-report",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
        ],
      },
    ],
  },
  {
    group: "General",
    menu: [
      {
        name: "Admin",
        icon: "toggle_on",
        submenu: [
          {
            name: "Menu",
            route: "general/administration/menu",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
          {
            icon: "toggle_on",
            name: "User Authentication",
            route: "general/administration/menuauthentication",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
          {
            icon: "toggle_on",
            name: "Group Authentication",
            route: "general/administration/groupauthentication",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
          {
            icon: "layers",
            name: "Import Data",
            route: "general/master/import-data",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
        ],
      },
      {
        name: "Employee",
        icon: "layers",
        submenu: [
          {
            name: "Category Cuti",
            route: "general/master/category-cuti",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
          {
            icon: "person",
            name: "Approve Cuti",
            route: "general/master/approve-cuti",
            permission: ["Y", "Y", "Y", "Y", "Y"],
          },
        ],
      },
    ],
  },
];

// const group = [];

// function cobaboba() {
//   before.map((element) => {
//     if (!group.includes(element.groupmenu)) {
//       group.push(element.groupmenu);
//     }
//   });
// }
// cobaboba();
// console.log(group);

let apiMenu = before.map((x) => {
  const container = x.menu;
  return container;
});
// console.log(apiMenu);

// ==========group============
const hasil = [];
const duplicate = new Set();
function cobacoba2(x) {
  x.forEach((task) => {
    if (duplicate.has(task.groupmenu)) return;
    hasil.push({ group: task.groupmenu });
    duplicate.add(task.groupmenu);
  });
}
cobacoba2(before);
console.log(hasil);

// ==============menu===============
const menuu = [];
const duplicateMenu = new Set();
function cobacoba3(x) {
  x.forEach((task) => {
    if (duplicateMenu.has(task.menu)) return;
    menuu.push({ name: task.menu });
    duplicateMenu.add(task.menu);
  });
}
cobacoba3(before);
console.log(menuu);

// ==========icon=============
const iconn = [];
const duplicateIcon = new Set();
function cobacoba4(x) {
  x.map((task) => {
    if (duplicateIcon.has(task.icon)) return;
    iconn.push(task.icon);
    duplicateIcon.add(task.icon);
  });
}
cobacoba4(before);
console.log(iconn);

hasil[0].menu = [menuu[0]];
hasil[1].menu = [menuu[1], menuu[2], menuu[3], menuu[4], menuu[5]];
hasil[2].menu = [menuu[6], menuu[7], menuu[8]];
hasil[3].menu = [menuu[9], menuu[10]];

menuu[0].icon = iconn[0];
menuu[1].icon = iconn[0];
menuu[2].icon = iconn[0];
menuu[3].icon = iconn[0];
menuu[4].icon = iconn[0];
menuu[5].icon = iconn[0];
menuu[6].icon = iconn[3];
menuu[7].icon = iconn[4];
menuu[8].icon = iconn[7];
menuu[9].icon = iconn[12];
menuu[10].icon = iconn[0];

console.log(hasil[0]);
console.log(hasil[1]);
console.log(hasil[2]);
console.log(hasil[3]);
